# Generated by Django 4.2.6 on 2023-11-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc_cust', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='key',
            field=models.CharField(max_length=500),
        ),
    ]
