# Generated by Django 4.2.6 on 2023-11-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc_cust', '0002_alter_prescription_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='key',
            field=models.CharField(max_length=1500),
        ),
    ]
